site_name: PaliGemma2 · ScienceQA MLOps
site_author: Yuxin_Duc
docs_dir: source

theme:
  language: en
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.sections

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Usage: usage.md
  - API reference: reference.md
